title: "Remote theme example"
remote_theme: pmarsceill/just-the-docs
search_enabled: true

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true
